package com.smartplugin.android.logic.model



 data class MqttStatusResponse(
    /**
     * The id of the client
     */
    val deviceId: String,
    /**
     * The state of the system.
     */
    val state: String,
    /**
     * The LED status.
     */
    val led: String,
    /**
     * The version of the system.
     */
    val version: String,
    /**
     * The debug mode status.
     */
    val debug: String,
    /**
     * The information about the system.
     */
    val info: String,
    /**
     * The on status of the system.
     */
    val on: String,
    /**
     * The countdown timer for the system.
     */
    val countdown: String,
    /**
     * The start time of the system.
     */
    val starttime: String,
    /**
     * The end time of the system.
     */
    val endtime: String,
    /**
     * The timer for the system.
     */
    val timer: String,
    /**
     * The reverse status of the system.
     */
    val reverse: String,
    /**
     * The voltage of the system.
     */
    val voltage: String,
    /**
     * The current of the system.
     */
    val current: String,
    /**
     * The power of the system.
     */
    val power: String,
    /**
     * The energy of the system.
     */
    val energy: String,
    /**
     * The frequency of the system.
     */
    val freq: String,
    /**
     * The power statuses of the system.
     */
    val pows: String,
    /**
     * The time of the system.
     */
    val time: String
) {
    // Constructors, getters, setters, and other methods can be automatically generated by Kotlin.

}